#!/usr/bin/env python3
"""업계별 캘린더 빌더 — template.html + 아래 설정으로 {slug}/index.html 생성.
사용: python3 build.py  (industry-calendars 디렉토리에서)"""
import os

BASE = os.path.dirname(os.path.abspath(__file__))
TPL = open(os.path.join(BASE, 'template.html'), encoding='utf-8').read()

GFONT_COMMON = "family=Noto+Sans+KR:wght@300;400;500;700&family=Noto+Serif+KR:wght@400;600"

def vars_block(d, indent='    '):
    return '\n'.join(f"{indent}{k}:{v};" for k, v in d.items())

COMMON_LIGHT = {
    '--line': 'rgba(20,20,20,.14)', '--line-soft': 'rgba(20,20,20,.07)',
    '--live': '#2F7D42', '--live-bg': 'rgba(47,125,66,.1)',
    '--shadow': '0 1px 2px rgba(20,20,20,.05),0 8px 28px rgba(20,20,20,.07)',
    '--chip-on-ink': '#FFFFFF',
}
COMMON_DARK = {
    '--line': 'rgba(238,235,230,.16)', '--line-soft': 'rgba(238,235,230,.07)',
    '--live': '#7CC98F', '--live-bg': 'rgba(124,201,143,.13)',
    '--shadow': '0 1px 2px rgba(0,0,0,.3),0 10px 32px rgba(0,0,0,.35)',
    '--chip-on-ink': '#141414',
}

def hex_rgba(h, a):
    h = h.lstrip('#')
    r, g, b = int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16)
    return f'rgba({r},{g},{b},{a})'

def MONO_L(point):
    """블랙앤화이트 라이트 팔레트 + 포인트 컬러 1색"""
    return {'--bg':'#FBFBFA','--card':'#FFFFFF','--ink':'#141414','--sub':'#6B6B6B',
            '--brand':'#141414','--brand-soft':'rgba(0,0,0,.04)',
            '--acc':point,'--acc-soft':hex_rgba(point,'.09'),
            '--c1':point,'--c2':point,'--c3':point,'--c4':point,'--c5':point}

def MONO_D(point):
    """블랙앤화이트 다크 팔레트 + 포인트 컬러 1색"""
    return {'--bg':'#0E0E0E','--card':'#181818','--ink':'#F2F0EC','--sub':'#9C9C9C',
            '--brand':'#F2F0EC','--brand-soft':'rgba(255,255,255,.05)',
            '--acc':point,'--acc-soft':hex_rgba(point,'.13'),
            '--c1':point,'--c2':point,'--c3':point,'--c4':point,'--c5':point}

INDUSTRIES = {}

# ────────────────────────── 뷰티 ──────────────────────────
INDUSTRIES['beauty'] = dict(
    title='BEAUTY CALENDAR — 1%CLUB 뷰티 인텔리전스',
    desc='뷰티 업계 마케터가 알아야 할 글로벌·국내 이벤트 캘린더',
    favicon='🌸',
    gfont='family=Cormorant+Garamond:ital,wght@0,400;0,600;1,400',
    display_font='"Cormorant Garamond"',
    eyebrow='BEAUTY INTELLIGENCE',
    h1_en='The Beauty Calendar', h1_ko='뷰티 마케터의 1년',
    lede='뷰티 업계 마케터가 반드시 알아야 할 박람회·어워즈·기프팅 시즌·레드카펫 모먼트를 한눈에. 이벤트마다 마케팅 앵글과 준비 타이밍을 함께 담았습니다.',
    footer_tag='Beauty Industry Intelligence',
    light=MONO_L('#C64E6E'),
    dark=MONO_D('#E288A2'),
    playbook_title='뷰티 론칭 리듬',
    playbook_lede='뷰티 마케팅은 시즌 컬렉션과 기프팅 모멘텀의 반복입니다. 론칭 90일 전 기획이 완성돼 있어야 시딩과 리뷰 웨이브를 놓치지 않습니다.',
    playbook_cards=[
        ('D-90','컬렉션·에디션 기획','시즌 한정 에디션·기프트 세트 기획 확정. 홀리데이는 8월, 설·춘절은 11월이 데드라인.'),
        ('D-30','시딩 & 티저','인플루언서·프레스 시딩 발송, 티저 캠페인 시작. 리뷰 콘텐츠가 론칭일에 맞춰 터지도록 역산.'),
        ('D-14','리뷰 웨이브','시딩 리뷰·언박싱 콘텐츠 집중 발행 구간. 검색량 상승을 광고로 증폭.'),
        ('D-DAY','론칭','공식 론칭 + 팝업·리테일 연계. 첫 72시간 UGC 모니터링과 리그램 대응.'),
        ('D+14','리캡 & 재고 전략','판매 데이터 리뷰, 베스트셀러 증산·추가 프로모션 결정. 다음 시즌 기획에 반영.'),
    ],
    data_js=r"""
const CATS = {
  trade:{label:'박람회·업계', color:'var(--c1)'},
  awards:{label:'어워즈·랭킹', color:'var(--c2)'},
  seasonal:{label:'시즌·기프팅', color:'var(--c3)'},
  culture:{label:'레드카펫·컬처', color:'var(--c4)'},
  korea:{label:'K-뷰티 모먼트', color:'var(--c5)'},
};

const EVENTS = [
  {s:'2026-08-22', e:'2026-08-25', cat:'korea', title:'서울뷰티위크 2026', place:'서울 DDP',
   angle:'서울시 주관 K-뷰티 대표 행사 — 신진 브랜드·글로벌 바이어 총집결.',
   prep:'참가·제휴는 7월 중 컨택 마감. 참관만 해도 하반기 트렌드 소스.'},
  {s:'2026-09-01', e:'2026-09-07', cat:'culture', title:'서울패션위크 S/S 2027', place:'서울 DDP + 도심 랜드마크',
   angle:'25주년 — DDP + 덕수궁길·홍제유연·흥천사 등 도심 랜드마크로 확장. 런웨이 백스테이지 뷰티 — K-디자이너 쇼 메이크업 트렌드가 다음 시즌 룩의 예고편.',
   prep:'—'},
  {s:'2026-09-10', e:'2026-10-06', cat:'culture', title:'글로벌 패션먼스 S/S 2027 (NY→런던→밀라노→파리)', place:'뉴욕·런던·밀라노·파리',
   angle:'백스테이지 뷰티 트렌드의 원천. 파리(9/28–10/6)가 뷰티 하우스(디올·샤넬) 화제성 피크.',
   prep:'쇼 직후 "다음 시즌 메이크업 트렌드" 콘텐츠 선점.'},
  {s:'2026-09-24', e:'2026-09-26', cat:'seasonal', title:'추석 — 뷰티 기프트 시즌', place:'한국',
   angle:'프리미엄 스킨케어·향수 선물세트 시즌. 백화점 뷰티관 프로모션 피크.',
   prep:'세트 구성·패키지는 8월 초 확정이 표준.'},
  {s:'2026-10-26', e:'2026-11-30', cat:'seasonal', title:'홀리데이 컬렉션 론칭 시즌', place:'글로벌',
   angle:'연중 최대 화제성 — 어드벤트 캘린더·홀리데이 리미티드 대전. 발표 즉시 품절 경쟁이 뉴스가 되는 구간.',
   prep:'홀리데이 기획은 8월 확정, 10월 말 론칭이 표준 캘린더.'},
  {s:'2026-11-10', e:'2026-11-13', cat:'trade', title:'코스모프로프 아시아 홍콩', place:'홍콩 HKCEC·AWE',
   angle:'아시아 최대 뷰티 B2B 박람회 — K-뷰티 수출·ODM 트렌드의 현장.',
   prep:'바이어 미팅 캘린더 10월 중 확정.'},
  {s:'2026-11-11', e:'2026-11-11', cat:'seasonal', title:'광군제 (싱글스 데이)', place:'중국',
   angle:'중국 뷰티 소비 최대의 날 — 티몰·더우인 랭킹이 중국 시장 성적표.',
   prep:'—'},
  {s:'2026-11-19', e:'2026-11-19', cat:'korea', title:'수능 — 수험생 뷰티 리셋 시즌', place:'한국',
   angle:'"수능 끝 피부 관리 시작" — 수험생·N수생 타깃 스킨케어/시술 수요가 열리는 날.',
   prep:'수능 직후 주말 겨냥 프로모션 11월 초 준비.'},
  {s:'2026-11-23', e:'2026-11-30', cat:'seasonal', title:'블랙프라이데이 → 사이버먼데이', place:'글로벌',
   angle:'세포라·아마존 뷰티 세일 — 직구 가이드형 콘텐츠 저장수 높음.',
   prep:'—'},
  {s:'2026-12-01', e:'2026-12-25', cat:'seasonal', title:'홀리데이 기프팅 피크', place:'글로벌·한국',
   angle:'향수·프리미엄 세트 선물 수요 연중 최대. 12월은 향수의 달.',
   prep:'—'},
  {s:'2026-12-07', e:'2026-12-20', cat:'korea', title:'올리브영 어워즈&페스타', place:'서울', approx:true,
   angle:'K-뷰티 연간 성적표 — 어워즈 수상 = 이듬해 매대·마케팅의 핵심 크레딧.',
   prep:'수상 시 즉시 보도자료·상세페이지 뱃지 반영 준비.'},
  {s:'2027-01-06', e:'2027-01-09', cat:'trade', title:'CES — 뷰티테크', place:'라스베가스', approx:true,
   angle:'뷰티 디바이스·AI 피부 진단 — 뷰티테크 신제품이 글로벌 언론을 타는 무대.',
   prep:'—'},
  {s:'2027-02-06', e:'2027-02-09', cat:'seasonal', title:'설 연휴 + 중국 춘절', place:'한국·중화권',
   angle:'명절 선물세트 + 춘절 중화권 수요(면세·다이고·샤오홍슈) 동시 피크.',
   prep:'선물세트 1월 초 오픈, 춘절 캠페인은 샤오홍슈 병행.'},
  {s:'2027-03-14', e:'2027-03-14', cat:'seasonal', title:'화이트데이', place:'한국·일본',
   angle:'향수·립 기프팅 — 밸런타인 후속 웨이브.',
   prep:'—'},
  {s:'2027-03-18', e:'2027-03-21', cat:'trade', title:'코스모프로프 볼로냐 (제58회)', place:'볼로냐',
   angle:'세계 최대 뷰티 박람회 — 글로벌 원료·패키징·트렌드의 총본산.',
   prep:'—'},
  {s:'2027-03-14', e:'2027-03-14', cat:'culture', title:'아카데미 시상식 — 레드카펫 뷰티', place:'LA', approx:true,
   angle:'셀럽 레드카펫 메이크업 해부 콘텐츠 — "○○ 립 정보" 검색 폭증 구간.',
   prep:'당일 밤 실시간 대응 체제.'},
  {s:'2027-04-01', e:'2027-04-12', cat:'korea', title:'벚꽃 시즌 — 봄 에디션', place:'한국', approx:true,
   angle:'벚꽃 리미티드 에디션·봄 신상 캠페인의 비주얼 피크.',
   prep:'봄 에디션은 2월 확정, 3월 중순 론칭.'},
  {s:'2027-04-22', e:'2027-04-24', cat:'korea', title:'코스모뷰티 서울', place:'서울 코엑스', approx:true,
   angle:'국내 화장품·미용 산업 박람회 — 에스테틱·디바이스 트렌드.',
   prep:'—'},
  {s:'2027-05-03', e:'2027-05-03', cat:'culture', title:'Met Gala 2027', place:'뉴욕',
   angle:'연중 최대 뷰티 룩 화제성 — 멧갈라 뷰티 해부 콘텐츠.',
   prep:'—'},
  {s:'2027-05-11', e:'2027-05-22', cat:'culture', title:'칸 영화제', place:'칸', approx:true,
   angle:'뷰티 하우스 앰배서더(로레알·디올) 레드카펫 캠페인 시즌.',
   prep:'—'},
  {s:'2027-06-01', e:'2027-08-15', cat:'seasonal', title:'선케어·서머 시즌', place:'글로벌·한국',
   angle:'선케어 성수기 + 워터프루프·쿨링 카테고리 피크.',
   prep:'선케어 캠페인은 4월 말 시작이 표준.'},
  {s:'2027-08-20', e:'2027-08-24', cat:'korea', title:'서울뷰티위크 2027', place:'서울', approx:true,
   angle:'K-뷰티 대표 행사 — 하반기 트렌드 소스.',
   prep:'—'},
  {s:'2027-09-14', e:'2027-09-16', cat:'seasonal', title:'추석 — 뷰티 기프트 시즌', place:'한국',
   angle:'프리미엄 선물세트 시즌.',
   prep:'8월 초 세트 확정.'},
  {s:'2027-09-09', e:'2027-10-05', cat:'culture', title:'글로벌 패션먼스 S/S 2028', place:'4대 도시', approx:true,
   angle:'백스테이지 뷰티 트렌드 시즌.',
   prep:'—'},
  {s:'2027-10-25', e:'2027-11-30', cat:'seasonal', title:'홀리데이 컬렉션 론칭 시즌', place:'글로벌',
   angle:'어드벤트 캘린더·홀리데이 리미티드 대전.',
   prep:'8월 기획 확정 → 10월 말 론칭.'},
  {s:'2027-11-09', e:'2027-11-12', cat:'trade', title:'코스모프로프 아시아 홍콩', place:'홍콩', approx:true,
   angle:'아시아 최대 뷰티 B2B.',
   prep:'—'},
  {s:'2027-11-11', e:'2027-11-11', cat:'seasonal', title:'광군제', place:'중국',
   angle:'중국 뷰티 소비 최대의 날.',
   prep:'—'},
  {s:'2027-12-01', e:'2027-12-25', cat:'seasonal', title:'홀리데이 기프팅 피크 + 올리브영 어워즈', place:'글로벌·한국',
   angle:'향수·세트 선물 피크, K-뷰티 연간 결산.',
   prep:'—'},
];

const MONTH_THEMES = {
  '2026-07':{theme:'서머 시즌 한복판', note:'홀리데이 컬렉션 기획(8월 데드라인)을 지금 확정할 시점.'},
  '2026-08':{theme:'서울뷰티위크 & 홀리데이 기획 마감', super:true},
  '2026-09':{theme:'패션먼스 백스테이지 & 추석 기프팅'},
  '2026-10':{theme:'홀리데이 론칭 개막', super:true},
  '2026-11':{theme:'광군제 → 블프 — 커머스 슈퍼먼스', super:true},
  '2026-12':{theme:'기프팅 피크 & K-뷰티 결산'},
  '2027-01':{theme:'뷰티테크 & 설 준비'},
  '2027-02':{theme:'설·춘절 기프팅'},
  '2027-03':{theme:'볼로냐 & 레드카펫 시즌'},
  '2027-04':{theme:'벚꽃 에디션 & 봄 신상'},
  '2027-05':{theme:'멧갈라 → 칸 — 레드카펫 하이시즌'},
  '2027-06':{theme:'선케어 성수기 개막'},
  '2027-07':{theme:'서머 시즌'},
  '2027-08':{theme:'서울뷰티위크 & 홀리데이 기획 마감', super:true},
  '2027-09':{theme:'패션먼스 & 추석'},
  '2027-10':{theme:'홀리데이 론칭 개막', super:true},
  '2027-11':{theme:'광군제 → 블프 슈퍼먼스', super:true},
  '2027-12':{theme:'기프팅 피크 & 결산'},
};
""",
)

# ────────────────────────── 패션 ──────────────────────────
INDUSTRIES['fashion'] = dict(
    title='FASHION CALENDAR — 1%CLUB 패션 인텔리전스',
    desc='패션 업계 마케터가 알아야 할 패션위크·어워즈·리테일 시즌 캘린더',
    favicon='🖤',
    gfont='family=Playfair+Display:ital,wght@0,400;0,600;1,400',
    display_font='"Playfair Display"',
    eyebrow='FASHION INTELLIGENCE',
    h1_en='The Fashion Calendar', h1_ko='패션 마케터의 1년',
    lede='4대 패션위크부터 어워즈·리테일 시즌까지, 패션 업계 마케터가 반드시 알아야 할 글로벌·국내 이벤트를 한눈에.',
    footer_tag='Fashion Industry Intelligence',
    light=MONO_L('#C8102E'),
    dark=MONO_D('#F0506A'),
    playbook_title='시즌 마케팅 리듬',
    playbook_lede='패션은 6개월 앞을 사는 산업입니다. 컬렉션 발표 → 캠페인 → 드롭 → 세일의 사이클에 마케팅 캘린더를 정렬하세요.',
    playbook_cards=[
        ('쇼 시즌','컬렉션 발표','패션위크 기간 실시간 커버리지 + 프런트로·백스테이지 콘텐츠. 다음 시즌 바잉·화보의 원천.'),
        ('D-60','캠페인 론칭','시즌 캠페인 비주얼 공개 — 셀럽·앰배서더 화보로 화제성 선점.'),
        ('D-30','드롭 & 팝업','신상품 입고·한정 드롭·팝업 오픈. 대기줄이 곧 콘텐츠.'),
        ('시즌 중','스타일링 콘텐츠','착장 제안·하울·룩북 — 구매 전환 구간의 핵심 콘텐츠.'),
        ('시즌 말','세일 & 아카이브','정기 세일·아울렛 전환 + 시즌 리캡. 다음 시즌 티저로 연결.'),
    ],
    data_js=r"""
const CATS = {
  fw:{label:'패션위크', color:'var(--c1)'},
  awards:{label:'어워즈', color:'var(--c2)'},
  retail:{label:'리테일·시즌', color:'var(--c3)'},
  culture:{label:'레드카펫·컬처', color:'var(--c4)'},
  korea:{label:'코리아 모먼트', color:'var(--c5)'},
};

const EVENTS = [
  {s:'2026-09-01', e:'2026-09-07', cat:'korea', title:'서울패션위크 S/S 2027', place:'서울 DDP + 도심 랜드마크',
   angle:'25주년 — DDP(비즈니스·트레이드쇼 9/4~6, 74개 브랜드) + 덕수궁길·홍제유연·흥천사 등 도심 랜드마크로 확장. K-디자이너와 셀럽 프런트로 — 서울이 글로벌 패션 지도에 오르는 주간.',
   prep:'쇼·프레젠테이션 초청 리스트 8월 중 확보.'},
  {s:'2026-09-10', e:'2026-09-15', cat:'fw', title:'뉴욕 패션위크 S/S 2027', place:'뉴욕',
   angle:'패션먼스 개막 (CFDA 공식, 톰브라운 클로징). 스트리트 스타일·프런트로 셀럽 콘텐츠.',
   prep:'—'},
  {s:'2026-09-22', e:'2026-09-28', cat:'fw', title:'밀라노 패션위크 S/S 2027', place:'밀라노',
   angle:'프라다 오프닝 — 이탈리아 하우스 중심 커버리지.',
   prep:'—'},
  {s:'2026-09-17', e:'2026-09-21', cat:'fw', title:'런던 패션위크 S/S 2027', place:'런던',
   angle:'브리티시 하우스·신진 디자이너 발굴 무대.',
   prep:'—'},
  {s:'2026-09-28', e:'2026-10-06', cat:'fw', title:'파리 패션위크 S/S 2027', place:'파리',
   angle:'패션먼스 피날레, 68개 쇼 — 샤넬·디올·루이비통. 화제성 연중 최대 구간.',
   prep:'데일리 하이라이트 체제 + 쇼 직후 트렌드 정리 선점.'},
  {s:'2026-11-02', e:'2026-11-02', cat:'awards', title:'CFDA 패션 어워즈', place:'뉴욕 자연사박물관',
   angle:'미국 패션의 오스카 — 수상자·레드카펫 룩 화제성.',
   prep:'—'},
  {s:'2026-11-11', e:'2026-11-11', cat:'retail', title:'광군제 (싱글스 데이)', place:'중국',
   angle:'중국 패션 커머스 최대의 날 — 티몰 럭셔리 성적표.',
   prep:'—'},
  {s:'2026-11-23', e:'2026-11-30', cat:'retail', title:'블랙프라이데이 → 사이버먼데이', place:'글로벌',
   angle:'명품 플랫폼(파페치·마이테레사) 세일 대전 — 직구 가이드 콘텐츠 피크.',
   prep:'—'},
  {s:'2026-11-30', e:'2026-11-30', cat:'awards', title:'The Fashion Awards (영국 패션어워즈)', place:'런던 로열 앨버트 홀',
   angle:'글로벌 패션계 연말 결산 — 올해의 디자이너·모델. 레드카펫 화제성.',
   prep:'—'},
  {s:'2026-12-01', e:'2026-12-25', cat:'retail', title:'홀리데이 캠페인 & 기프팅 시즌', place:'글로벌',
   angle:'하우스별 홀리데이 캠페인 필름 대전 + 선물 가이드 시즌.',
   prep:'기프트 가이드는 11월 중순 발행.'},
  {s:'2027-01-12', e:'2027-01-15', cat:'fw', title:'피티 워모 111', place:'피렌체', approx:true,
   angle:'클래식 멘즈웨어 성지 — 스트리트 스냅의 원조 무대.',
   prep:'—'},
  {s:'2027-01-15', e:'2027-01-18', cat:'fw', title:'밀라노 멘즈 F/W 2027', place:'밀라노', approx:true,
   angle:'멘즈 시즌 개막.',
   prep:'—'},
  {s:'2027-01-19', e:'2027-01-24', cat:'fw', title:'파리 멘즈 패션위크 F/W 2027', place:'파리',
   angle:'멘즈 메인 — 루이비통·디올 맨 쇼.',
   prep:'—'},
  {s:'2027-01-25', e:'2027-01-28', cat:'fw', title:'파리 오트쿠튀르 S/S 2027', place:'파리', approx:true,
   angle:'장인정신·아틀리에 스토리 — 헤리티지 콘텐츠의 정점.',
   prep:'—'},
  {s:'2027-02-01', e:'2027-02-05', cat:'korea', title:'서울패션위크 F/W 2027', place:'서울 DDP', approx:true,
   angle:'F/W 시즌 K-패션 무대.',
   prep:'—'},
  {s:'2027-02-06', e:'2027-02-09', cat:'retail', title:'설 연휴 + 중국 춘절', place:'한국·중화권',
   angle:'춘절 캡슐 컬렉션·기프팅 — 중화권 최대 소비 시즌.',
   prep:'춘절 캠페인은 12월 확정이 표준.'},
  {s:'2027-02-12', e:'2027-02-17', cat:'fw', title:'뉴욕 패션위크 F/W 2027', place:'뉴욕', approx:true,
   angle:'F/W 패션먼스 개막.',
   prep:'—'},
  {s:'2027-02-23', e:'2027-03-01', cat:'fw', title:'밀라노 패션위크 F/W 2027', place:'밀라노', approx:true,
   angle:'이탈리아 하우스 F/W.',
   prep:'—'},
  {s:'2027-03-02', e:'2027-03-10', cat:'fw', title:'파리 패션위크 F/W 2027', place:'파리', approx:true,
   angle:'F/W 피날레 — 릴레이 커버리지의 정점.',
   prep:'—'},
  {s:'2027-03-14', e:'2027-03-14', cat:'culture', title:'아카데미 시상식', place:'LA', approx:true,
   angle:'레드카펫 드레스 해부 — 하우스별 드레싱 성적표.',
   prep:'—'},
  {s:'2027-05-03', e:'2027-05-03', cat:'culture', title:'Met Gala 2027 — "Costume Art"', place:'뉴욕',
   angle:'패션계 최대 화제성 이벤트 — 베스트 드레스 리캡은 당일 밤 실시간 대응.',
   prep:'—'},
  {s:'2027-05-11', e:'2027-05-22', cat:'culture', title:'칸 영화제', place:'칸', approx:true,
   angle:'레드카펫 꾸뛰르 대전 + K-셀럽 앰배서더 모먼트.',
   prep:'—'},
  {s:'2027-06-10', e:'2027-06-10', cat:'awards', title:'LVMH 프라이즈 파이널', place:'파리', approx:true,
   angle:'차세대 디자이너의 등용문 — 신진 디자이너 발굴 콘텐츠.',
   prep:'—'},
  {s:'2027-06-22', e:'2027-06-27', cat:'fw', title:'파리 멘즈 S/S 2028', place:'파리', approx:true,
   angle:'멘즈·쿠튀르 연속 주간의 시작.',
   prep:'—'},
  {s:'2027-07-05', e:'2027-07-08', cat:'fw', title:'파리 오트쿠튀르 F/W 2027', place:'파리', approx:true,
   angle:'쿠튀르 위크.',
   prep:'—'},
  {s:'2027-09-01', e:'2027-09-07', cat:'korea', title:'서울패션위크 S/S 2028', place:'서울', approx:true,
   angle:'K-패션 S/S 무대.',
   prep:'—'},
  {s:'2027-09-09', e:'2027-10-05', cat:'fw', title:'글로벌 패션먼스 S/S 2028', place:'뉴욕→런던→밀라노→파리', approx:true,
   angle:'S/S 2028 시즌 릴레이 — 파리 피날레.',
   prep:'—'},
  {s:'2027-11-01', e:'2027-11-30', cat:'awards', title:'어워즈 시즌 (CFDA·Fashion Awards)', place:'뉴욕·런던', approx:true,
   angle:'연말 패션 결산 어워즈 릴레이.',
   prep:'—'},
  {s:'2027-11-11', e:'2027-11-29', cat:'retail', title:'광군제 → 블랙프라이데이', place:'글로벌',
   angle:'연말 커머스 슈퍼시즌.',
   prep:'—'},
  {s:'2027-12-01', e:'2027-12-25', cat:'retail', title:'홀리데이 캠페인 시즌', place:'글로벌',
   angle:'하우스 홀리데이 필름 + 기프팅.',
   prep:'—'},
];

const MONTH_THEMES = {
  '2026-07':{theme:'프리시즌', note:'9월 패션먼스 커버리지·캠페인 준비의 달.'},
  '2026-08':{theme:'패션먼스 D-30'},
  '2026-09':{theme:'패션먼스 — 서울에서 파리까지', super:true},
  '2026-10':{theme:'파리 피날레 & 시즌 정리', super:true},
  '2026-11':{theme:'어워즈 & 커머스 시즌', super:true},
  '2026-12':{theme:'홀리데이 캠페인'},
  '2027-01':{theme:'멘즈 & 쿠튀르', super:true},
  '2027-02':{theme:'F/W 패션먼스 개막'},
  '2027-03':{theme:'파리 F/W 피날레', super:true},
  '2027-04':{theme:'시즌 브레이크'},
  '2027-05':{theme:'멧갈라 → 칸 — 레드카펫 하이시즌', super:true},
  '2027-06':{theme:'멘즈 S/S & LVMH 프라이즈'},
  '2027-07':{theme:'쿠튀르 위크'},
  '2027-08':{theme:'패션먼스 D-30'},
  '2027-09':{theme:'패션먼스 S/S 2028', super:true},
  '2027-10':{theme:'파리 피날레'},
  '2027-11':{theme:'어워즈 & 커머스 시즌', super:true},
  '2027-12':{theme:'홀리데이 캠페인'},
};
""",
)

# ────────────────────────── 하이주얼리 ──────────────────────────
INDUSTRIES['jewelry'] = dict(
    title='HIGH JEWELRY CALENDAR — 1%CLUB 하이주얼리 인텔리전스',
    desc='하이주얼리 업계 마케터가 알아야 할 페어·경매·기프팅·레드카펫 캘린더',
    favicon='💎',
    gfont='family=Cormorant:ital,wght@0,400;0,600;1,400',
    display_font='"Cormorant"',
    eyebrow='HIGH JEWELRY INTELLIGENCE',
    h1_en='The High Jewelry Calendar', h1_ko='하이주얼리 마케터의 1년',
    lede='하이주얼리 하우스와 파인주얼리 브랜드가 알아야 할 페어·경매·쿠튀르 신작·기프팅 시즌·레드카펫 모먼트를 한눈에.',
    footer_tag='High Jewelry Intelligence',
    light=MONO_L('#157A5C'),
    dark=MONO_D('#5BC4A0'),
    playbook_title='하이주얼리 모먼트 운영법',
    playbook_lede='하이주얼리는 신작 발표(쿠튀르 위크)와 기프팅 시즌, 레드카펫이 화제성의 3축입니다. 각 모먼트를 역산해 캠페인을 정렬하세요.',
    playbook_cards=[
        ('신작','쿠튀르 위크 공개','1월·7월 파리 쿠튀르 위크가 하이주얼리 컬렉션의 공식 발표 무대 — 프레스·VIP 프리뷰가 함께 움직인다.'),
        ('D-45','기프팅 캠페인','크리스마스·밸런타인·춘절 기프팅 캠페인은 45일 전 론칭 — 구매 리드타임이 긴 카테고리.'),
        ('레드카펫','착장 모먼트','시상식·영화제 착장은 실시간 화제성의 원천 — 착용 즉시 "누가 무엇을" 콘텐츠 대응.'),
        ('경매','시장 검증','제네바·홍콩 경매 결과는 브랜드 자산가치의 공인 지표 — 낙찰가 뉴스를 헤리티지 콘텐츠로 전환.'),
        ('브라이덜','웨딩 시즌','봄·가을 웨딩 시즌은 브라이덜 라인 매출 피크 — 상담 예약 캠페인 선행.'),
    ],
    data_js=r"""
const CATS = {
  fair:{label:'페어·전시', color:'var(--c1)'},
  maison:{label:'메종·신작', color:'var(--c2)'},
  gift:{label:'기프팅·브라이덜', color:'var(--c3)'},
  redcarpet:{label:'레드카펫', color:'var(--c4)'},
  auction:{label:'경매', color:'var(--c5)'},
};

const EVENTS = [
  {s:'2026-09-14', e:'2026-09-20', cat:'fair', title:'Jewellery & Gem WORLD 홍콩 (JGW)', place:'홍콩 AWE·HKCEC',
   angle:'세계 최대 주얼리 B2B 페어 — 원석·완제품 트렌드와 아시아 시장 분위기의 바로미터.',
   prep:'바이어·서플라이어 미팅 8월 중 확정.'},
  {s:'2026-09-24', e:'2026-09-26', cat:'gift', title:'추석 — 프리미엄 기프팅', place:'한국',
   angle:'골드·파인주얼리 명절 선물 수요. 백화점 주얼리관 프로모션.',
   prep:'—'},
  {s:'2026-10-01', e:'2026-11-15', cat:'gift', title:'가을 웨딩 시즌 — 브라이덜 피크', place:'한국',
   angle:'예물 상담·브라이덜 라인 매출 피크. 웨딩밴드·다이아 콘텐츠 시즌.',
   prep:'상담 예약 캠페인은 8~9월 선행.'},
  {s:'2026-10-05', e:'2026-10-12', cat:'auction', title:'소더비·크리스티 홍콩 가을 경매 (매그니피센트 주얼스)', place:'홍콩', approx:true,
   angle:'아시아 주얼리 경매 시즌 — 낙찰가가 곧 시장 뉴스.',
   prep:'—'},
  {s:'2026-11-09', e:'2026-11-15', cat:'auction', title:'제네바 주얼리 경매 위크 (크리스티·소더비·필립스)', place:'제네바', approx:true,
   angle:'세계 주얼리 경매의 정점 — 히스토릭 스톤 낙찰 뉴스가 글로벌 헤드라인.',
   prep:'—'},
  {s:'2026-11-27', e:'2026-11-27', cat:'redcarpet', title:'청룡영화상 — K-셀럽 주얼리', place:'서울', approx:true,
   angle:'국내 최대 레드카펫 — 앰배서더 착장이 국내 화제성 피크.',
   prep:'착장 협찬은 3~4주 전 확정.'},
  {s:'2026-12-01', e:'2026-12-25', cat:'gift', title:'홀리데이 기프팅 피크', place:'글로벌·한국',
   angle:'하이주얼리 연중 최대 기프팅 시즌 — 홀리데이 캠페인·윈도 디스플레이 대전.',
   prep:'캠페인은 11월 중순 론칭 (D-45 원칙).'},
  {s:'2027-01-25', e:'2027-01-28', cat:'maison', title:'파리 오트쿠튀르 위크 — 하이주얼리 신작 공개', place:'파리', approx:true,
   angle:'까르띠에·반클리프·부쉐론 등 신작 컬렉션의 공식 발표 무대 — 연중 최대 신작 모먼트.',
   prep:'신작 국내 입고·프레스 데이 일정을 발표 직후 확정.'},
  {s:'2027-02-06', e:'2027-02-09', cat:'gift', title:'설 + 중국 춘절 기프팅', place:'한국·중화권',
   angle:'춘절은 중화권 골드·주얼리 최대 소비 시즌.',
   prep:'12월 말 캠페인 확정.'},
  {s:'2027-02-14', e:'2027-02-14', cat:'gift', title:'밸런타인데이', place:'글로벌',
   angle:'프러포즈·기프팅 모먼트 — 하트·러브 모티프 라인 피크.',
   prep:'1월 초 캠페인 론칭 (D-45).'},
  {s:'2027-03-11', e:'2027-03-18', cat:'fair', title:'TEFAF 마스트리흐트', place:'네덜란드', approx:true,
   angle:'세계 최고 권위 아트·앤티크 페어 — 빈티지 하이주얼리 컬렉터의 무대.',
   prep:'—'},
  {s:'2027-03-14', e:'2027-03-14', cat:'redcarpet', title:'아카데미 시상식', place:'LA', approx:true,
   angle:'하이주얼리 각축전 — "오스카 주얼리 결산" 콘텐츠는 매년 검증된 포맷.',
   prep:'당일 밤 실시간 대응.'},
  {s:'2027-04-05', e:'2027-04-11', cat:'fair', title:'Watches & Wonders Geneva 2027', place:'제네바',
   angle:'주얼리 워치·하이주얼리 하우스(까르띠에·피아제) 신작 무대.',
   prep:'—'},
  {s:'2027-04-10', e:'2027-06-13', cat:'gift', title:'봄 웨딩 시즌 — 브라이덜 피크', place:'한국',
   angle:'예물 성수기 — 브라이덜 상담·컨시어지 캠페인.',
   prep:'2~3월 상담 예약 캠페인 선행.'},
  {s:'2027-05-03', e:'2027-05-03', cat:'redcarpet', title:'Met Gala 2027', place:'뉴욕',
   angle:'하이주얼리 스테이트먼트 피스의 최대 무대.',
   prep:'—'},
  {s:'2027-05-06', e:'2027-05-09', cat:'fair', title:'GemGenève', place:'제네바', approx:true,
   angle:'원석·빈티지 주얼리 전문 페어 — 젬 딜러·컬렉터 네트워크.',
   prep:'—'},
  {s:'2027-05-10', e:'2027-05-17', cat:'auction', title:'제네바 주얼리 경매 위크 (봄)', place:'제네바', approx:true,
   angle:'상반기 경매 피크 — 컬러 다이아·히스토릭 피스 뉴스.',
   prep:'—'},
  {s:'2027-05-11', e:'2027-05-22', cat:'redcarpet', title:'칸 영화제 — 쇼파드의 무대', place:'칸', approx:true,
   angle:'레드카펫 하이주얼리의 정점 — K-셀럽 착장 모먼트.',
   prep:'—'},
  {s:'2027-06-04', e:'2027-06-07', cat:'fair', title:'JCK 라스베가스', place:'라스베가스', approx:true,
   angle:'북미 최대 주얼리 트레이드쇼.',
   prep:'—'},
  {s:'2027-07-05', e:'2027-07-08', cat:'maison', title:'파리 오트쿠튀르 위크 — 하이주얼리 신작', place:'파리', approx:true,
   angle:'하반기 신작 컬렉션 공개 — 연중 두 번째 대형 신작 모먼트.',
   prep:'—'},
  {s:'2027-09-13', e:'2027-09-19', cat:'fair', title:'JGW 홍콩', place:'홍콩', approx:true,
   angle:'세계 최대 주얼리 B2B 페어.',
   prep:'—'},
  {s:'2027-09-14', e:'2027-09-16', cat:'gift', title:'추석 기프팅', place:'한국',
   angle:'명절 골드·파인주얼리 수요.',
   prep:'—'},
  {s:'2027-10-01', e:'2027-11-14', cat:'gift', title:'가을 웨딩 시즌', place:'한국',
   angle:'브라이덜 피크.',
   prep:'—'},
  {s:'2027-11-08', e:'2027-11-14', cat:'auction', title:'제네바 주얼리 경매 위크 (가을)', place:'제네바', approx:true,
   angle:'연말 경매 피크.',
   prep:'—'},
  {s:'2027-12-01', e:'2027-12-25', cat:'gift', title:'홀리데이 기프팅 피크', place:'글로벌',
   angle:'연중 최대 기프팅 시즌.',
   prep:'11월 중순 캠페인 론칭.'},
];

const MONTH_THEMES = {
  '2026-07':{theme:'하반기 준비', note:'가을 브라이덜·홀리데이 캠페인 기획 시점.'},
  '2026-08':{theme:'JGW·가을 시즌 D-30'},
  '2026-09':{theme:'JGW 홍콩 & 추석', super:true},
  '2026-10':{theme:'브라이덜 & 경매 시즌 개막'},
  '2026-11':{theme:'제네바 경매 & 홀리데이 론칭', super:true},
  '2026-12':{theme:'기프팅 피크', super:true},
  '2027-01':{theme:'쿠튀르 신작 모먼트', super:true},
  '2027-02':{theme:'춘절 & 밸런타인 기프팅'},
  '2027-03':{theme:'TEFAF & 레드카펫'},
  '2027-04':{theme:'W&W 제네바 & 봄 브라이덜', super:true},
  '2027-05':{theme:'멧갈라 → 칸 → 경매 — 하이시즌', super:true},
  '2027-06':{theme:'JCK & 웨딩 시즌'},
  '2027-07':{theme:'쿠튀르 신작 (하반기)', super:true},
  '2027-08':{theme:'하반기 준비'},
  '2027-09':{theme:'JGW & 추석'},
  '2027-10':{theme:'브라이덜 시즌'},
  '2027-11':{theme:'경매 & 홀리데이 론칭', super:true},
  '2027-12':{theme:'기프팅 피크', super:true},
};
""",
)

# ────────────────────────── 시계 ──────────────────────────
INDUSTRIES['watches'] = dict(
    title='WATCH CALENDAR — 1%CLUB 시계 인텔리전스',
    desc='시계 업계 마케터가 알아야 할 페어·경매·어워즈·앰배서더 모먼트 캘린더',
    favicon='⌚',
    gfont='family=EB+Garamond:ital,wght@0,400;0,600;1,400',
    display_font='"EB Garamond"',
    eyebrow='HOROLOGY INTELLIGENCE',
    h1_en='The Watch Calendar', h1_ko='시계 마케터의 1년',
    lede='워치스&원더스부터 GPHG·경매·스포츠 앰배서더 모먼트까지, 시계 업계 마케터가 알아야 할 1년을 한눈에.',
    footer_tag='Horology Intelligence',
    light=MONO_L('#2C5AA0'),
    dark=MONO_D('#7FA9E0'),
    playbook_title='노벨티 사이클 운영법',
    playbook_lede='시계 마케팅의 1년은 신작(노벨티) 발표 → 국내 입고 → 앰배서더 모먼트 → 연말 기프팅으로 흐릅니다. 4월 제네바가 모든 것의 시작점입니다.',
    playbook_cards=[
        ('발표','노벨티 시즌','4월 W&W 제네바 + 1월 LVMH 워치위크 — 신작 발표 즉시 하이라이트·가격 정리 콘텐츠 선점.'),
        ('D+60','국내 입고','신작 국내 입고·부티크 프리뷰 — 실물 콘텐츠와 웨이팅리스트 마케팅의 구간.'),
        ('상시','앰배서더 모먼트','F1·테니스·골프 등 스폰서 이벤트마다 손목 위 시계가 콘텐츠 — 스포츠 캘린더와 연동.'),
        ('11월','어워즈 & 경매','GPHG 수상과 제네바 경매 낙찰가 — 브랜드 가치의 공인 지표를 콘텐츠로 전환.'),
        ('연말','기프팅 시즌','홀리데이·춘절 기프팅 — 엔트리 럭셔리 라인의 판매 피크.'),
    ],
    data_js=r"""
const CATS = {
  fair:{label:'페어·신작', color:'var(--c1)'},
  award:{label:'어워즈', color:'var(--c2)'},
  auction:{label:'경매', color:'var(--c3)'},
  culture:{label:'스포츠·앰배서더', color:'var(--c4)'},
  gift:{label:'기프팅·리테일', color:'var(--c5)'},
};

const EVENTS = [
  {s:'2026-08-30', e:'2026-09-13', cat:'culture', title:'US 오픈 테니스 — 롤렉스 모먼트', place:'뉴욕',
   angle:'롤렉스 공식 타임키퍼 — 코트 위 앰배서더 손목 콘텐츠.',
   prep:'—'},
  {s:'2026-09-02', e:'2026-09-06', cat:'fair', title:'제네바 워치 데이즈 (제7회)', place:'제네바',
   angle:'하반기 신작 발표 무대 — 독립 브랜드·중견 메종의 노벨티 시즌.',
   prep:'발표 즉시 신작 하이라이트 콘텐츠.'},
  {s:'2026-09-24', e:'2026-09-26', cat:'gift', title:'추석 — 시계 기프팅', place:'한국',
   angle:'명절 프리미엄 선물 수요 — 백화점 워치관 프로모션.',
   prep:'—'},
  {s:'2026-10-09', e:'2026-10-11', cat:'culture', title:'F1 싱가포르 GP', place:'마리나 베이',
   angle:'롤렉스·태그호이어의 무대 — 패덕 손목 위 콘텐츠와 리미티드 에디션 뉴스.',
   prep:'—'},
  {s:'2026-11-02', e:'2026-11-15', cat:'auction', title:'제네바 가을 시계 경매 (필립스·크리스티·소더비)', place:'제네바', approx:true,
   angle:'빈티지·그랜드 컴플리케이션 낙찰가가 곧 업계 헤드라인 — 시장 온도계.',
   prep:'주요 랏 프리뷰 콘텐츠 사전 준비.'},
  {s:'2026-11-07', e:'2026-11-07', cat:'award', title:'GPHG 시상식 (제26회)', place:'제네바 BFM',
   angle:'시계업계의 오스카 — 수상작 정리 콘텐츠는 매년 검증된 포맷.',
   prep:'수상 직후 카테고리별 결산 콘텐츠.'},
  {s:'2026-12-01', e:'2026-12-25', cat:'gift', title:'홀리데이 기프팅 피크', place:'글로벌·한국',
   angle:'엔트리 럭셔리 워치 판매 피크 — 기프트 가이드 시즌.',
   prep:'가이드 콘텐츠 11월 중순 발행.'},
  {s:'2027-01-18', e:'2027-01-21', cat:'fair', title:'LVMH 워치 위크 2027', place:'유럽', approx:true,
   angle:'불가리·태그호이어·위블로·제니스 신년 노벨티 — 한 해 신작 레이스의 개막.',
   prep:'—'},
  {s:'2027-02-06', e:'2027-02-09', cat:'gift', title:'설 + 춘절 기프팅', place:'한국·중화권',
   angle:'중화권 워치 소비 시즌 — 골드·레드 모티프 에디션.',
   prep:'—'},
  {s:'2027-04-05', e:'2027-04-11', cat:'fair', title:'Watches & Wonders Geneva 2027', place:'제네바',
   angle:'시계업계 최대 행사 — 롤렉스·파텍·까르띠에 신작. 브라이틀링·갈렛·유니버설 제네브 신규 합류. 퍼블릭 데이 4/9–11.',
   prep:'발표 주간 데일리 하이라이트 체제 + 신작 가격·스펙 정리 선점. 국내 입고 일정 즉시 확인.'},
  {s:'2027-05-08', e:'2027-05-16', cat:'auction', title:'제네바 봄 시계 경매', place:'제네바', approx:true,
   angle:'필립스 제네바 워치 옥션 — 상반기 시장 온도계.',
   prep:'—'},
  {s:'2027-05-27', e:'2027-05-30', cat:'culture', title:'F1 모나코 GP — 태그호이어의 무대', place:'몬테카를로', approx:true,
   angle:'모터스포츠×워치 헤리티지의 정점.',
   prep:'—'},
  {s:'2027-06-28', e:'2027-07-11', cat:'culture', title:'윔블던 — 롤렉스 모먼트', place:'런던', approx:true,
   angle:'센터코트 롤렉스 시계탑 — 테니스×워치 헤리티지 콘텐츠.',
   prep:'—'},
  {s:'2027-08-30', e:'2027-09-12', cat:'culture', title:'US 오픈 테니스', place:'뉴욕', approx:true,
   angle:'롤렉스 타임키퍼 모먼트.',
   prep:'—'},
  {s:'2027-09-01', e:'2027-09-05', cat:'fair', title:'제네바 워치 데이즈 2027', place:'제네바', approx:true,
   angle:'하반기 노벨티 시즌.',
   prep:'—'},
  {s:'2027-09-14', e:'2027-09-16', cat:'gift', title:'추석 기프팅', place:'한국',
   angle:'명절 프리미엄 선물 수요.',
   prep:'—'},
  {s:'2027-10-08', e:'2027-10-10', cat:'culture', title:'F1 싱가포르 GP', place:'마리나 베이', approx:true,
   angle:'아시아 모터스포츠×워치 위켄드.',
   prep:'—'},
  {s:'2027-11-01', e:'2027-11-14', cat:'auction', title:'제네바 가을 경매 + Only Watch 2027', place:'제네바', approx:true,
   angle:'격년 자선 경매 Only Watch — 유니크 피스 낙찰가로 업계가 들썩이는 이벤트.',
   prep:'—'},
  {s:'2027-11-06', e:'2027-11-06', cat:'award', title:'GPHG 시상식 (제27회)', place:'제네바', approx:true,
   angle:'시계업계 연간 결산.',
   prep:'—'},
  {s:'2027-12-01', e:'2027-12-25', cat:'gift', title:'홀리데이 기프팅 피크', place:'글로벌',
   angle:'워치 기프트 가이드 시즌.',
   prep:'—'},
];

const MONTH_THEMES = {
  '2026-07':{theme:'하반기 준비', note:'9월 제네바 워치 데이즈·연말 기프팅 기획 시점.'},
  '2026-08':{theme:'US 오픈 개막'},
  '2026-09':{theme:'제네바 워치 데이즈 — 하반기 노벨티', super:true},
  '2026-10':{theme:'F1 싱가포르 & 앰배서더 시즌'},
  '2026-11':{theme:'GPHG & 경매 — 결산의 달', super:true},
  '2026-12':{theme:'홀리데이 기프팅'},
  '2027-01':{theme:'LVMH 워치위크 — 노벨티 개막', super:true},
  '2027-02':{theme:'춘절 기프팅'},
  '2027-03':{theme:'W&W D-30 — 프리뷰 시즌'},
  '2027-04':{theme:'Watches & Wonders — 연중 최대', super:true},
  '2027-05':{theme:'경매 & 모나코'},
  '2027-06':{theme:'윔블던 개막'},
  '2027-07':{theme:'윔블던 & 서머'},
  '2027-08':{theme:'US 오픈'},
  '2027-09':{theme:'제네바 워치 데이즈', super:true},
  '2027-10':{theme:'F1 & 앰배서더 시즌'},
  '2027-11':{theme:'GPHG & Only Watch — 결산', super:true},
  '2027-12':{theme:'홀리데이 기프팅'},
};
""",
)

# ────────────────────────── 웰니스 & 롱지비티 ──────────────────────────
INDUSTRIES['wellness'] = dict(
    title='WELLNESS & LONGEVITY CALENDAR — 1%CLUB 웰니스 인텔리전스',
    desc='웰니스·롱지비티 업계가 알아야 할 서밋·시즌 모멘텀·글로벌 데이 캘린더',
    favicon='🌿',
    gfont='family=Fraunces:opsz,wght@9..144,400;9..144,600',
    display_font='"Fraunces"',
    eyebrow='WELLNESS & LONGEVITY INTELLIGENCE',
    h1_en='The Wellness Calendar', h1_ko='웰니스 마케터의 1년',
    lede='웰니스·롱지비티 업계가 알아야 할 글로벌 서밋·시즌 모멘텀·러닝 캘린더·글로벌 데이를 한눈에. 이벤트마다 마케팅 앵글과 준비 타이밍을 담았습니다.',
    footer_tag='Wellness & Longevity Intelligence',
    light=MONO_L('#4C8B5C'),
    dark=MONO_D('#8FC49C'),
    playbook_title='웰니스 모멘텀 운영법',
    playbook_lede='웰니스 마케팅은 "결심의 순간"을 잡는 게임입니다. 새해·여름 전·마라톤 시즌 등 행동이 바뀌는 모멘텀에 캠페인을 정렬하세요.',
    playbook_cards=[
        ('1월','신년 리셋','연중 최대 모멘텀 — 새해 결심(운동·디톡스·수면) 수요 폭발. 캠페인은 12월 중순 론칭.'),
        ('D-90','바디 시즌 역산','여름 바디·바캉스 준비는 3월부터 — "여름까지 90일" 프레임이 검증된 포맷.'),
        ('러닝','마라톤 캘린더','3월 서울마라톤·11월 JTBC마라톤 전후로 러닝 기어·리커버리 수요 피크.'),
        ('글로벌 데이','캠페인 훅','수면의 날·요가의 날·정신건강의 날 — 브랜드 메시지를 걸 수 있는 공인된 훅.'),
        ('서밋','트렌드 선점','글로벌 웰니스 서밋 리포트가 이듬해 업계 키워드를 결정 — 발표 즉시 해설 콘텐츠 선점.'),
    ],
    data_js=r"""
const CATS = {
  summit:{label:'서밋·컨퍼런스', color:'var(--c1)'},
  seasonal:{label:'시즌 모멘텀', color:'var(--c2)'},
  sport:{label:'러닝·스포츠', color:'var(--c3)'},
  day:{label:'글로벌 데이', color:'var(--c4)'},
  korea:{label:'코리아 모먼트', color:'var(--c5)'},
};

const EVENTS = [
  {s:'2026-07-15', e:'2026-08-31', cat:'seasonal', title:'서머 리트릿 · 웰니스 트래블 성수기', place:'글로벌·한국',
   angle:'휴가철 리트릿·스파·디지털 디톡스 수요 피크 — 휴가 후 번아웃 회복 콘텐츠까지 연결.',
   prep:'9월 "리셋" 캠페인을 8월 중 준비.'},
  {s:'2026-09-28', e:'2026-10-02', cat:'summit', title:'롱지비티 인베스터스 컨퍼런스', place:'스위스', approx:true,
   angle:'롱지비티 산업 자본의 흐름을 읽는 자리 — 안티에이징을 넘어 "수명 연장 산업"의 시그널.',
   prep:'—'},
  {s:'2026-10-10', e:'2026-10-10', cat:'day', title:'세계 정신건강의 날', place:'글로벌',
   angle:'멘탈 웰니스 캠페인 훅 — 명상·수면·스트레스 관리 메시지의 공인된 날.',
   prep:'캠페인 2주 전 준비.'},
  {s:'2026-11-01', e:'2026-11-01', cat:'sport', title:'JTBC 서울마라톤', place:'서울 (상암→올림픽공원)',
   angle:'국내 최대 러닝 축제 — 러닝 크루 문화·기어·리커버리 수요 피크.',
   prep:'러너 타깃 캠페인은 10월 초 시작 (훈련 막바지 구간).'},
  {s:'2026-11-10', e:'2026-11-13', cat:'summit', title:'글로벌 웰니스 서밋 2026 (20주년)', place:'푸켓 앙사나 라구나',
   angle:'세계 웰니스 산업의 다보스 — 여기서 발표되는 트렌드 리포트가 이듬해 업계 키워드를 결정.',
   prep:'서밋 직후 "2027 웰니스 트렌드" 해설 콘텐츠 선점.'},
  {s:'2026-11-19', e:'2026-11-19', cat:'korea', title:'수능 — 회복의 시작', place:'한국',
   angle:'수험생·학부모의 번아웃 회복 시즌 — 수면·피부·체력 리셋 수요.',
   prep:'—'},
  {s:'2026-12-15', e:'2027-01-31', cat:'seasonal', title:'연말 디톡스 → 신년 리셋 시즌', place:'글로벌·한국',
   angle:'웰니스 연중 최대 모멘텀 — 새해 결심(운동·다이어트·수면·금주) 수요 폭발. "1월의 헬스장" 현상.',
   prep:'신년 캠페인은 12월 중순 론칭이 표준 — 1월 1일엔 이미 늦다.'},
  {s:'2026-12-21', e:'2026-12-21', cat:'day', title:'세계 명상의 날 (UN)', place:'글로벌',
   angle:'연말 마인드풀니스 캠페인 훅.',
   prep:'—'},
  {s:'2027-01-06', e:'2027-01-09', cat:'summit', title:'CES — 디지털 헬스·슬립테크', place:'라스베가스', approx:true,
   angle:'웨어러블·슬립테크·AI 헬스 신제품의 무대 — 롱지비티 테크 트렌드의 최전선.',
   prep:'—'},
  {s:'2027-03-05', e:'2027-03-05', cat:'day', title:'세계 수면의 날', place:'글로벌', approx:true,
   angle:'슬립 이코노미 캠페인 훅 — 수면 리추얼·침구·슬립테크 콘텐츠.',
   prep:'—'},
  {s:'2027-03-21', e:'2027-03-21', cat:'sport', title:'서울마라톤 (동아마라톤)', place:'서울 광화문→잠실',
   angle:'국내 러닝 시즌의 공식 개막 — 봄 러닝 붐의 정점.',
   prep:'러닝 캠페인 2월 시작.'},
  {s:'2027-03-22', e:'2027-06-15', cat:'seasonal', title:'여름까지 90일 — 바디 시즌', place:'한국·글로벌',
   angle:'바디프로필·다이어트·피트니스 수요가 여름을 향해 상승하는 구간.',
   prep:'"D-90" 프레임 캠페인은 3월 말 론칭.'},
  {s:'2027-04-03', e:'2027-04-18', cat:'korea', title:'벚꽃 러닝 · 아웃도어 시즌 개막', place:'한국', approx:true,
   angle:'벚꽃 런·피크닉·아웃도어 요가 — 야외 활동 재개의 비주얼 모먼트.',
   prep:'—'},
  {s:'2027-06-12', e:'2027-06-12', cat:'day', title:'글로벌 웰니스 데이', place:'글로벌',
   angle:'전 세계 웰니스 브랜드가 동시에 움직이는 날 — 무료 클래스·오픈 하우스 포맷.',
   prep:'참여 프로그램 5월 중 기획.'},
  {s:'2027-06-21', e:'2027-06-21', cat:'day', title:'국제 요가의 날', place:'글로벌',
   angle:'요가·마인드풀니스 캠페인 훅 — 대규모 야외 클래스 시즌.',
   prep:'—'},
  {s:'2027-07-15', e:'2027-08-31', cat:'seasonal', title:'서머 리트릿 · 웰니스 트래블 성수기', place:'글로벌',
   angle:'리트릿·스파 성수기.',
   prep:'—'},
  {s:'2027-09-27', e:'2027-10-01', cat:'summit', title:'롱지비티 인베스터스 컨퍼런스', place:'스위스', approx:true,
   angle:'롱지비티 산업 시그널.',
   prep:'—'},
  {s:'2027-10-10', e:'2027-10-10', cat:'day', title:'세계 정신건강의 날', place:'글로벌',
   angle:'멘탈 웰니스 캠페인 훅.',
   prep:'—'},
  {s:'2027-11-07', e:'2027-11-07', cat:'sport', title:'JTBC 서울마라톤 2027', place:'서울', approx:true,
   angle:'가을 러닝 시즌 피날레.',
   prep:'—'},
  {s:'2027-11-09', e:'2027-11-12', cat:'summit', title:'글로벌 웰니스 서밋 2027', place:'미정', approx:true,
   angle:'2028 웰니스 트렌드의 발원지.',
   prep:'—'},
  {s:'2027-12-15', e:'2027-12-31', cat:'seasonal', title:'연말 디톡스 → 신년 리셋 준비', place:'글로벌',
   angle:'신년 모멘텀 준비 구간.',
   prep:'12월 중순 신년 캠페인 론칭.'},
];

const MONTH_THEMES = {
  '2026-07':{theme:'서머 리트릿 성수기', note:'여름 피크 + 9월 리셋 캠페인 준비.'},
  '2026-08':{theme:'서머 피크 → 가을 리셋 준비'},
  '2026-09':{theme:'가을 리셋 & 롱지비티 시그널'},
  '2026-10':{theme:'러닝 시즌 & 멘탈 웰니스'},
  '2026-11':{theme:'서울마라톤 & 글로벌 웰니스 서밋', super:true},
  '2026-12':{theme:'디톡스 → 신년 리셋 론칭', super:true},
  '2027-01':{theme:'신년 리셋 — 연중 최대 모멘텀', super:true},
  '2027-02':{theme:'리셋 유지 & 러닝 준비'},
  '2027-03':{theme:'서울마라톤 & 바디 시즌 개막', super:true},
  '2027-04':{theme:'아웃도어 시즌'},
  '2027-05':{theme:'바디 시즌 피크'},
  '2027-06':{theme:'웰니스 데이 & 요가의 날'},
  '2027-07':{theme:'서머 리트릿 성수기'},
  '2027-08':{theme:'서머 피크'},
  '2027-09':{theme:'가을 리셋'},
  '2027-10':{theme:'러닝 시즌'},
  '2027-11':{theme:'마라톤 & 웰니스 서밋', super:true},
  '2027-12':{theme:'신년 리셋 준비', super:true},
};
""",
)


def render(slug, cfg):
    pb_cards = '\n'.join(
        f'      <div class="pb"><div class="d">{d}</div><div class="t">{t}</div><p>{p}</p></div>'
        for d, t, p in cfg['playbook_cards'])
    light = dict(cfg['light']); light.update(COMMON_LIGHT)
    dark = dict(cfg['dark']); dark.update(COMMON_DARK)
    html = TPL
    reps = {
        '{{TITLE}}': cfg['title'], '{{DESC}}': cfg['desc'], '{{FAVICON}}': cfg['favicon'],
        '{{GFONT_FAMILIES}}': GFONT_COMMON + '&' + cfg['gfont'],
        '{{DISPLAY_FONT}}': cfg['display_font'],
        '{{VARS_LIGHT}}': vars_block(light), '{{VARS_DARK}}': vars_block(dark, '      '),
        '{{EYEBROW}}': cfg['eyebrow'], '{{H1_EN}}': cfg['h1_en'], '{{H1_KO}}': cfg['h1_ko'],
        '{{LEDE}}': cfg['lede'],
        '{{PLAYBOOK_TITLE}}': cfg['playbook_title'], '{{PLAYBOOK_LEDE}}': cfg['playbook_lede'],
        '{{PLAYBOOK_CARDS}}': pb_cards, '{{FOOTER_TAG}}': cfg['footer_tag'],
        '{{DATA_JS}}': cfg['data_js'].strip(),
    }
    for k, v in reps.items():
        html = html.replace(k, v)
    assert '{{' not in html, f'unreplaced token in {slug}'
    os.makedirs(os.path.join(BASE, slug), exist_ok=True)
    with open(os.path.join(BASE, slug, 'index.html'), 'w', encoding='utf-8') as f:
        f.write(html)
    print(f'built {slug}/index.html ({len(html)} bytes)')


if __name__ == '__main__':
    for slug, cfg in INDUSTRIES.items():
        render(slug, cfg)
